In [2]:
import pandas as pd 
import json

In [3]:
#Need to load in JSON dictionaries in order to work with pandas
#starting with one slice for testing 
with open("../data/mpd.slice.0-999.json") as f:
    data = json.load(f)

In [4]:
#This pandas method transform the nested dictionaries into a flat table
pd.json_normalize(data)

,playlists,info.generated_on,info.slice,info.version
0,"[{'name': 'Throwbacks', 'collaborative': 'fals...",2017-12-03 08:41:42.057563,0-999,v1

In [5]:
#For the bronze layer we want to have the important data in its raw form
#In this circumstance we care about the playlists, so we use the record_path parameter to specify 
normaldata = pd.json_normalize(data, record_path="playlists") #json_normalize use allows us to unwrap nested data according to where we have our records using the 'record_path=' parameter
#which in this case is the playlists
print(type(normaldata))
normaldata
#Note that this is missing the metadata for the slice

<class 'pandas.DataFrame'>

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,Throwbacks,false,0,1493424000,52,47,1,"[{'pos': 0, 'artist_name': 'Missy Elliott', 't...",6,11532414,37,NaN
1,Awesome Playlist,false,1,1506556800,39,23,1,"[{'pos': 0, 'artist_name': 'Survivor', 'track_...",5,11656470,21,NaN
2,korean,false,2,1505692800,64,51,1,"[{'pos': 0, 'artist_name': 'Hoody', 'track_uri...",18,14039958,31,NaN
3,mat,false,3,1501027200,126,107,1,"[{'pos': 0, 'artist_name': 'Camille Saint-Saën...",4,28926058,86,NaN
4,90s,false,4,1401667200,17,16,2,"[{'pos': 0, 'artist_name': 'The Smashing Pumpk...",7,4335282,16,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
995,old,false,995,1507852800,41,40,1,"[{'pos': 0, 'artist_name': 'Katrina', 'track_u...",8,9917901,36,NaN
996,Daze,false,996,1479254400,17,17,1,"[{'pos': 0, 'artist_name': 'PARTYNEXTDOOR', 't...",13,3699248,15,NaN
997,rap,false,997,1410307200,119,98,1,"[{'pos': 0, 'artist_name': 'LoveRance', 'track...",63,27538723,82,NaN
998,Country,false,998,1507939200,108,75,1,"[{'pos': 0, 'artist_name': 'Hunter Hayes', 'tr...",37,24950143,40,NaN
999,thinking of you,false,999,1507766400,44,43,1,"[{'pos': 0, 'artist_name': 'Pvris', 'track_uri...",34,9065801,37,NaN

In [6]:
#Testing dataframe to parquet file conversion
normaldata.to_parquet

<bound method DataFrame.to_parquet of                  name collaborative  pid  modified_at  num_tracks  num_albums  \
0          Throwbacks         false    0   1493424000          52          47
1    Awesome Playlist         false    1   1506556800          39          23
2             korean          false    2   1505692800          64          51
3                 mat         false    3   1501027200         126         107
4                 90s         false    4   1401667200          17          16
..                ...           ...  ...          ...         ...         ...
995               old         false  995   1507852800          41          40
996              Daze         false  996   1479254400          17          17
997               rap         false  997   1410307200         119          98
998           Country         false  998   1507939200         108          75
999   thinking of you         false  999   1507766400          44          43

     num_followers                                             tracks  \
0                1  [{'pos': 0, 'artist_name': 'Missy Elliott', 't...
1                1  [{'pos': 0, 'artist_name': 'Survivor', 'track_...
2                1  [{'pos': 0, 'artist_name': 'Hoody', 'track_uri...
3                1  [{'pos': 0, 'artist_name': 'Camille Saint-Saën...
4                2  [{'pos': 0, 'artist_name': 'The Smashing Pumpk...
..             ...                                                ...
995              1  [{'pos': 0, 'artist_name': 'Katrina', 'track_u...
996              1  [{'pos': 0, 'artist_name': 'PARTYNEXTDOOR', 't...
997              1  [{'pos': 0, 'artist_name': 'LoveRance', 'track...
998              1  [{'pos': 0, 'artist_name': 'Hunter Hayes', 'tr...
999              1  [{'pos': 0, 'artist_name': 'Pvris', 'track_uri...

     num_edits  duration_ms  num_artists description
0            6     11532414           37         NaN
1            5     11656470           21         NaN
2           18     14039958           31         NaN
3            4     28926058           86         NaN
4            7      4335282           16         NaN
..         ...          ...          ...         ...
995          8      9917901           36         NaN
996         13      3699248           15         NaN
997         63     27538723           82         NaN
998         37     24950143           40         NaN
999         34      9065801           37         NaN

[1000 rows x 12 columns]>

## To follow the best practices of a standard medallion architecture- we will also keep the meta data for slices in an 'info' table and a separate table for playlists

In [10]:
# Saving locally
import csv
with open ("../bronze/info4.csv",'a', newline = "") as file:
      testdata = pd.json_normalize(data)
      csvdata = testdata.to_csv()
      writer = csv.writer(file)
      writer.writerow(csvdata)

In [ ]:
# May have been writing to a csv twice
testdata= pd.json_normalize(data)
testdata.to_csv("../bronze/info5.csv") #success

In [ ]:
with open ("../bronze/info6.csv", "a", newline = "") as file:

In [ ]:
help(open)

Help on function open in module _io:

open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
    Open file and return a stream.  Raise OSError upon failure.

    file is either a text or byte string giving the name (and the path
    if the file isn't in the current working directory) of the file to
    be opened or an integer file descriptor of the file to be
    wrapped. (If a file descriptor is given, it is closed when the
    returned I/O object is closed, unless closefd is set to False.)

    mode is an optional string that specifies the mode in which the file
    is opened. It defaults to 'r' which means open for reading in text
    mode.  Other common values are 'w' for writing (truncating the file if
    it already exists), 'x' for creating and writing to a new file, and
    'a' for appending (which on some Unix systems, means that all writes
    append to the end of the file regardless of the current seek position).
    In text mode, if encoding is not specified the encoding used is platform
    dependent: locale.getencoding() is called to get the current locale encoding.
    (For reading and writing raw bytes use binary mode and leave encoding
    unspecified.) The available modes are:

    ========= ===============================================================
    Character Meaning
    --------- ---------------------------------------------------------------
    'r'       open for reading (default)
    'w'       open for writing, truncating the file first
    'x'       create a new file and open it for writing
    'a'       open for writing, appending to the end of the file if it exists
    'b'       binary mode
    't'       text mode (default)
    '+'       open a disk file for updating (reading and writing)
    ========= ===============================================================

    The default mode is 'rt' (open for reading text). For binary random
    access, the mode 'w+b' opens and truncates the file to 0 bytes, while
    'r+b' opens the file without truncation. The 'x' mode implies 'w' and
    raises an `FileExistsError` if the file already exists.

    Python distinguishes between files opened in binary and text modes,
    even when the underlying operating system doesn't. Files opened in
    binary mode (appending 'b' to the mode argument) return contents as
    bytes objects without any decoding. In text mode (the default, or when
    't' is appended to the mode argument), the contents of the file are
    returned as strings, the bytes having been first decoded using a
    platform-dependent encoding or using the specified encoding if given.

    buffering is an optional integer used to set the buffering policy.
    Pass 0 to switch buffering off (only allowed in binary mode), 1 to select
    line buffering (only usable in text mode), and an integer > 1 to indicate
    the size of a fixed-size chunk buffer.  When no buffering argument is
    given, the default buffering policy works as follows:

    * Binary files are buffered in fixed-size chunks; the size of the buffer
      is chosen using a heuristic trying to determine the underlying device's
      "block size" and falling back on `io.DEFAULT_BUFFER_SIZE`.
      On many systems, the buffer will typically be 4096 or 8192 bytes long.

    * "Interactive" text files (files for which isatty() returns True)
      use line buffering.  Other text files use the policy described above
      for binary files.

    encoding is the name of the encoding used to decode or encode the
    file. This should only be used in text mode. The default encoding is
    platform dependent, but any encoding supported by Python can be
    passed.  See the codecs module for the list of supported encodings.

    errors is an optional string that specifies how encoding errors are to
    be handled---this argument should not be used in binary mode. Pass
    'strict' to raise a ValueError exception if there is an encoding error
    (the default of None has the same effect), or pass 'ignore' to ignore
    errors. (Note that ignoring encoding errors can lead to data loss.)
    See the documentation for codecs.register or run 'help(codecs.Codec)'
    for a list of the permitted encoding error strings.

    newline controls how universal newlines works (it only applies to text
    mode). It can be None, '', '\n', '\r', and '\r\n'.  It works as
    follows:

    * On input, if newline is None, universal newlines mode is
      enabled. Lines in the input can end in '\n', '\r', or '\r\n', and
      these are translated into '\n' before being returned to the
      caller. If it is '', universal newline mode is enabled, but line
      endings are returned to the caller untranslated. If it has any of
      the other legal values, input lines are only terminated by the given
      string, and the line ending is returned to the caller untranslated.

    * On output, if newline is None, any '\n' characters written are
      translated to the system default line separator, os.linesep. If
      newline is '' or '\n', no translation takes place. If newline is any
      of the other legal values, any '\n' characters written are translated
      to the given string.

    If closefd is False, the underlying file descriptor will be kept open
    when the file is closed. This does not work when a file name is given
    and must be True in that case.

    A custom opener can be used by passing a callable as *opener*. The
    underlying file descriptor for the file object is then obtained by
    calling *opener* with (*file*, *flags*). *opener* must return an open
    file descriptor (passing os.open as *opener* results in functionality
    similar to passing None).

    open() returns a file object whose type depends on the mode, and
    through which the standard file operations such as reading and writing
    are performed. When open() is used to open a file in a text mode ('w',
    'r', 'wt', 'rt', etc.), it returns a TextIOWrapper. When used to open
    a file in a binary mode, the returned class varies: in read binary
    mode, it returns a BufferedReader; in write binary and append binary
    modes, it returns a BufferedWriter, and in read/write mode, it returns
    a BufferedRandom.

    It is also possible to use a string or bytearray as a file for both
    reading and writing. For strings StringIO can be used like a file
    opened in a text mode, and for bytes a BytesIO can be used like a file
    opened in a binary mode.